# Generated by Django 4.2.30 on 2026-05-21 04:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='화분 이름')),
                ('current_weight', models.FloatField(verbose_name='현재 무게(g)')),
                ('daily_decrease', models.FloatField(verbose_name='1일 감소량(g)')),
                ('water_threshold', models.FloatField(verbose_name='물주는 무게(g)')),
                ('season', models.CharField(choices=[('spring', '봄'), ('summer', '여름'), ('fall', '가을'), ('winter', '겨울')], max_length=10, verbose_name='현재 계절')),
                ('last_measured_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='마지막 측정 시각')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
            ],
            options={
                'verbose_name': '화분',
                'verbose_name_plural': '화분 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='물 준 시각')),
                ('weight_after', models.FloatField(verbose_name='물 준 후 무게(g)')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_logs', to='plants.plant', verbose_name='화분')),
            ],
            options={
                'verbose_name': '물주기 이력',
                'verbose_name_plural': '물주기 이력 목록',
                'ordering': ['-watered_at'],
            },
        ),
    ]
