# Generated by Django 4.2.30 on 2026-05-21 05:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def migrate_water_logs(apps, schema_editor):
    """
    기존 WaterLog 데이터를 신규 PlantLog 데이터(event_type='watered')로 안전하게 이전합니다.
    """
    WaterLog = apps.get_model('plants', 'WaterLog')
    PlantLog = apps.get_model('plants', 'PlantLog')
    
    for wl in WaterLog.objects.all():
        detail_msg = f"물 준 후 무게: {wl.weight_after}g"
        if wl.memo:
            detail_msg += f" / 메모: {wl.memo}"
            
        PlantLog.objects.create(
            plant=wl.plant,
            event_type='watered',
            created_at=wl.watered_at,
            weight_after=wl.weight_after,
            detail=detail_msg
        )

class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', '화분 등록'), ('watered', '물 줬어요'), ('updated', '설정 변경')], max_length=10, verbose_name='이벤트 종류')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='기록 시각')),
                ('weight_after', models.FloatField(blank=True, null=True, verbose_name='기록 시점 무게(g)')),
                ('detail', models.TextField(blank=True, verbose_name='상세 내용')),
            ],
            options={
                'verbose_name': '화분 이력 로그',
                'verbose_name_plural': '화분 이력 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='plant',
            name='season',
        ),
        migrations.AddField(
            model_name='plant',
            name='tip',
            field=models.TextField(blank=True, verbose_name='관리 Tip 메모'),
        ),
        migrations.AddField(
            model_name='plantlog',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='plants.plant', verbose_name='화분'),
        ),
        # 기존 WaterLog 데이터를 신규 PlantLog 테이블로 마이그레이션 실행
        migrations.RunPython(migrate_water_logs),
        # 데이터 이전이 완료된 후 구형 모델 제거
        migrations.DeleteModel(
            name='WaterLog',
        ),
    ]
