# Generated by Django 4.2.30 on 2026-05-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plantlog_remove_plant_season_plant_tip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('pin_hash', models.CharField(max_length=128, verbose_name='PIN 해시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입 일시')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 로그인 일시')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='plants.userprofile', verbose_name='소유 사용자'),
        ),
    ]
