# Generated by Django 4.2.30 on 2026-05-21 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='plants.userprofile', verbose_name='소유 사용자'),
        ),
    ]
