# Generated by Django 4.2.30 on 2026-05-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_alter_plant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='구글 캘린더 이벤트 ID'),
        ),
    ]
